### ISSUE TITLE
java_properties

### ISSUE THREAD

**Issue by zetan503** [dschlenk/opennms-cookbook#1]
Hey I am trying to get your cookbook setup on my server but ran into an error.
Any ideas? I gem installed java_properties on the chef-server.

LoadError
---------
cannot load such file -- java_properties

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/opennms/libraries/graph.rb:3:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/opennms/libraries/graph.rb:

  1:  $:.unshift *Dir[File.expand_path('../../files/default/vendor/gems/**/lib', __FILE__)]
  2:
  3>> require 'java_properties'
  4:
  5:  module Graph
  6:    def new_graph_file(file, node)
  7:      f = ::File.new("#{node['opennms']['conf']['home']}/etc/snmp-graph.properties.d/#{file}", "w")
  8:      ::File.open(f, "w"){ |file| file.puts(["reports=\n", "\n"]) }
  9:    end
 10:    def graph_file_exists?(filename, node)
 11:      ::File.exists?("#{node['opennms']['conf']['home']}/etc/snmp-graph.properties.d/#{filename}")
 12:    end

**Comment by dschlenk** [comment]
I'm using chef_gem for these dependencies now so this is resolved.
