### ISSUE TITLE
Recipe Compile Error in recipes/default.rb

### ISSUE THREAD

**Issue by cerntf** [dschlenk/opennms-cookbook#3]
Running this cookbook for OS: CentOS-6.5-x86_64

Getting the following recipe compile error:

==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef-4/chef-solo-1/cookbooks/op/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: LocalJumpError
==> default: --------------
==> default: no block given (yield)
==> default: 
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/opennms/recipes/default.rb:57:in `block in from_file'
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/opennms/recipes/default.rb:55:in `from_file'
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/op/recipes/default.rb:38:in `from_file'
==> default: 
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef-4/chef-solo-1/cookbooks/opennms/recipes/default.rb:
==> default: 
==> default:  50:  hostsfile_entry node['ipaddress'] do
==> default:  51:    hostname fqdn
==> default:  52:    action [:create_if_missing, :append]
==> default:  53:  end
==> default:  54:  
==> default:  55:  package "opennms" do
==> default:  56:    version "1.12.9-2"
==> default:  57>>   timeout 1200
==> default:  58:    action :install
==> default:  59:  end
==> default:  60:  
==> default:  61:  package "iplike" do
==> default:  62:    action :install
==> default:  63:  end
==> default:  64:  
==> default:  65:  package "perl-libwww-perl" do
==> default:  66:    action :install

Appears the timeout attribute is only available in the windows_package provider and breaks on other package providers.  I can get this to work by removing the timeout attribute at line 57 and overriding yum_timeout in my recipe  (i.e. Chef::Config[:yum_timeout] =1200).  I recommend changing your cookbook to do the same to make it more portable.

**Comment by dschlenk** [comment]
Thanks for the heads up. I'll be releasing a new version that targets 15 soon and will include this change.

**Comment by dschlenk** [comment]
I released 1.0.1 (supports 14.0.3) this evening with this change applied. Thanks for reporting the issue!
