### ISSUE TITLE
centos7: Newly released opennms version 23.0.0 broke the install of 22.0.2

### ISSUE THREAD

**Issue by emillbrandt** [dschlenk/opennms-cookbook#42]
Version 22.0.2 moved from the stable repo to the obsolete repo and this code https://github.com/dschlenk/opennms-cookbook/blob/develop/recipes/packages.rb#L60 is causing the 'obsolete' repo to not be indexed.  I am not clear on why it should not be?

A quick and dirty workaround I am using is to move the stable repo to the end of the branch list.
`node.default['opennms']['repos']['branches'] = %w(obsolete snapshot stable)`

I have only tested this on centos 7.5.

**Comment by dschlenk** [comment]
Hello! Thanks for reporting this. I'll rearrange the order. Hope to get a 23 supporting version out soon, too.

**Comment by dschlenk** [comment]
22.1.1 was just pushed to supermarket
